// 后台任务管理
export {
  BackgroundTaskManager,
  TaskScheduler,
  TaskHistoryStore,
  TaskHistoryManager,
  createTaskSnapshotStore,
  createTaskPersistenceAdapter,
  createTaskHistoryStore,
  createTaskStorage,
  createTaskPersistencePlugin,
  restorePendingFromPersistence,
  restorePendingFromSnapshots,
  IndexedDBAdapter,
  readJson,
  writeJson,
  getWebStorage,
} from './background-task-manager'

export type {
  BackgroundTask,
  BackgroundTaskManagerPlugin,
  BackgroundTaskManagerEventName,
  BackgroundTaskManagerListener,
  BackgroundTaskManagerOptions,
  BackgroundTaskStatus,
  EnqueueTaskOptions,
  TaskExecuteContext,
  TaskExecutor,
  ScheduledTask,
  TaskSchedulerOptions,
  TaskSchedulerEventName,
  TaskStorageBackend,
  TaskSnapshotStoreOptions,
  TaskHistoryStoreOptions,
  TaskStorageBundleOptions,
  TaskSnapshotStore,
  TaskHistoryEntry,
  TaskHistoryStats,
  TaskHistoryQuery,
  TaskPersistenceAdapter,
  TaskPersistenceOptions,
  StorageBackend,
  TaskHistoryOptions,
} from './background-task-manager'

// 任务执行链
export {
  TraceAll,
  TaskExecutionChain,
  TaskExecutionStackTracer,
  TraceCall,
  TraceEnter,
  TraceStep,
  TraceVar,
  createTraceVariable,
  createStackTracer,
  getLastTraceResult,
  getTraceStepMetadata,
  runTracedFlow,
} from './task-execution-chain'

export type {
  AddTaskExecutionNodeOptions,
  CompleteTaskExecutionNodeOptions,
  ConnectTaskExecutionNodeOptions,
  FailTaskExecutionNodeOptions,
  TaskExecutionEdge,
  TaskExecutionMermaidOptions,
  TaskExecutionNode,
  TaskExecutionNodeStatus,
  TaskExecutionRenderResult,
  RunTracedFlowOptions,
  TraceStepMetadata,
  TraceStepOptions,
  TracedFlowExecuteResult,
  TracedFlowRunContext,
} from './task-execution-chain/taskExecutionChain'

export type {
  StackTraceExecuteOptions,
  StackTraceRunContext,
  StackTraceStepOptions,
  TraceAllOptions,
  TraceCallOptions,
  TraceEnterExecuteResult,
  TraceEnterOptions,
  TraceVarOptions,
  TracedVariable,
} from './task-execution-chain/taskExecutionStackTracer'
